package com.hyunstyle.cleanarchitecture.presentation.base

import androidx.appcompat.app.AppCompatActivity
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.material.CircularProgressIndicator
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import com.hyunstyle.cleanarchitecture.presentation.base.compose.Red300

/**
 * Created by hyunstyle on 2022.02.01
 * Copyright (c) 2022 All rights reserved.
 */
abstract class BaseActivity<VM : BaseViewModel> : AppCompatActivity() {

    /**
     * viewModel inject
     */
    abstract val mViewModel: VM

    /**
     * common progress indicator
     * if use setContent with BaseTheme,
     *
     * this progressIndicator automatically generated by viewModel / liveData
     */
    @Composable
    fun ProgressIndicator(isDisplayed: Boolean) {
        if(isDisplayed) {
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .fillMaxHeight(),
                horizontalArrangement = Arrangement.Center,
                verticalAlignment = Alignment.CenterVertically
            ) {
                CircularProgressIndicator(
                    color = Red300
                )
            }
        }
    }

}